### ISSUE TITLE
Functions not working

### ISSUE THREAD

**Issue by mosessmax** [yinkakun/wakatime-github-commit#1]
On my function options, from my Netlify Dashboard, i don't see anything such as "Enable Scheduled Functions"

Also i tried to navigate to the Given Function Endpoint: this url: https://famous-crisp-9a6da9.netlify.app/.netlify/functions/log-tracked-time

I ran into this error below,

{"error":{"response":{"data":{"repository":null},"errors":[{"type":"NOT_FOUND","path":["repository"],"locations":[{"line":3,"column":5}],"message":"Could not resolve to a Repository with the name 'adebayo-moses/https://github.com/adebayo-moses/wakatime-github-commit'."}],"status":200,"headers":{}},"request":{"query":"\n query Repo($owner: String!, $repo: String!) {\n repository(name: $repo, owner: $owner) {\n defaultBranchRef {\n name\n target {\n ... on Commit {\n history(first: 1) {\n nodes {\n oid\n }\n }\n }\n }\n }\n }\n }\n","variables":{"owner":"adebayo-moses","repo":"https://github.com/adebayo-moses/wakatime-github-commit"}}}}

**Comment by yinkakun** [comment]
Looks like you used a repo url instead of rep name
